### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by terrycmk** [dysphie/nmrih-runners-only#1]
Runner does not collide and stacks each other

**Comment by dysphie** [comment]
That's standard zombie behavior and out of scope for this plugin.

If you would like to change that, change the relevant cvars:

| Cvar | Description | Default Value |
| --- | --- | --- |
| sv_zombie_collision_enabled | Whether or not zombie collision is enabled. | 1 |
| sv_zombie_collision_group_count | Number of collision groups for zombies to use. | 3 |
| sv_zombie_grease_fails | Number of failures before zombies have chance at switching collision group. | 2 |
| sv_zombie_grease_chance | Chance of switching collision group after failures. | 0.5 |
